### ISSUE TITLE
UI DESIGN IDEA

### ISSUE THREAD

**Issue by CSIYI** [nguyensjsu/fa18-202-polymorphers#12]
How do we want to design the UI? Keep the traditional TV version, or we can design it in a modern way.

**Comment by davidpmontes** [comment]
I think it would be cool to emulate the look of the modern tv show now as much as possible.

**Comment by adiosray** [comment]
Let’s start with the traditional TV, Blue Black design first, which would be easy to implement. But also you could figure out a modern design pattern

**Comment by adiosray** [comment]
Duplicate of #13
